version: 2.1

jobs:
  build:  
    docker: 
      - image: rowanto/docker-java8-mvn-nodejs-npm
      
    steps:
      - checkout
      - run: npm install -q
      - snyk/scan
orbs:
  snyk: snyk/snyk@0.0.10
