version: 2.1

jobs:
  build:  
    docker: 
      - image: atlassianlabs/docker-node-jdk-chrome-firefox
      
    steps:
      - checkout
      - run: npm install -q
      - snyk/scan
orbs:
  snyk: snyk/snyk@0.0.10
