version: 2.1

jobs:
  build:  
    docker: 
      - image: timbru31/java-node

    
    steps:
    
      steps:
      - checkout
      - run: npm install -q
      - snyk/scan
orbs:
  snyk: snyk/snyk@0.0.10
